# Jekyll 설정 파일입니다.

# 사이트 기본 정보
title:              "Sim's Devlog"
description:        "Backend Developer"
author_name:        "Sim Jonghan"
author_email:       simhani1@gmail.com
logo_url:           https://github.com/simhani1.png

# 소셜 링크
social:
    github:         https://github.com/simhani1
    instagram:
    linkedin:       https://www.linkedin.com/in/simhani1

# 사이트 설정
url:                https://simhani1.github.io
baseurl:
permalink:          /:categories/:title/
timezone:           Asia/Seoul
new_badge_period:   7

# 분석
google_analytics:

# 댓글
comments:
    repo:           simhani1/simhani1.github.io

# 좋아요 버튼 API
# like_api_base:

# 사이트 빌드
markdown:           kramdown
highlighter:        rouge
kramdown:
    input:          GFM
sass:
    style:          :compressed

# 기타 파라미터
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "README.ko.md", "CNAME", "Gemfile", "drafts", "_templates" ]
plugins:
  - jekyll-sitemap

# 조건마다 자동으로 적용할 기본 속성들
defaults:
  - scope:
      path:         ""
    values:
      layout:       "null"
  - scope:
      type:         "pages"
    values:
      layout:       "page"
  - scope:
      type:         "posts"
    values:
      layout:       "post"
      comments:     true
